trigger:
  branches:
    include:
      - main                           # CI on every push to main

variables:
  azureServiceConn: 'project-connection'        # ARM service‑connection name
  tfWorkingDir: '$(System.DefaultWorkingDirectory)/terraform'
  location: 'East US'
  resourceGroup: 'monitoring-rg'
  tfVersion: '1.8.4'                            # pick a stable version

pool:
  vmImage: 'ubuntu-latest'

stages:
# ─────────────────────────────────────────────────────
- stage: Terraform
  displayName: 'Init → Plan → Apply'
  jobs:
  - job: DeployMonitoring
    displayName: 'Provision monitoring stack'
    steps:

    # 1) Checkout repo
    - checkout: self

    # 2) Install / pin Terraform
    - task: TerraformInstaller@0                # ← changed @1 ➜ @0
      displayName: 'Install Terraform $(tfVersion)'
      inputs:
        terraformVersion: '$(tfVersion)'

    # 3) Terraform init
    - task: TerraformCLI@0                      # ← changed @1 ➜ @0
      displayName: 'terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(tfWorkingDir)'
        backendType: 'azurerm'
        ensureBackend: false          # backend declared in providers.tf
        environmentServiceName: '$(azureServiceConn)'

    # 4) Terraform plan  (plan file published as an artifact)
    - task: TerraformCLI@0
      displayName: 'terraform plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(tfWorkingDir)'
        environmentServiceName: '$(azureServiceConn)'
        commandOptions: |
          -input=false
          -var="location=$(location)"
          -var="resource_group_name=$(resourceGroup)"
          -var="action_group_email=alerts@example.com"
        publishPlanResults: 'plan'     # lets you inspect diff in UI

    # 5) (optional) manual approval gate → configure in “Environments”
    # ---------------------------------------------------------------
    # 6) Terraform apply
    - task: TerraformCLI@0
      displayName: 'terraform apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(tfWorkingDir)'
        environmentServiceName: '$(azureServiceConn)'
        commandOptions: |
          -auto-approve -input=false \
          -var="location=$(location)" \
          -var="resource_group_name=$(resourceGroup)" \
          -var="action_group_email=alerts@example.com"
